server.address=127.0.0.1
server.port=18087
spring.r2dbc.url=r2dbc:h2:mem:///usersdb?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.sql.init.mode=always
spring.webflux.multipart.max-disk-usage-per-part=5MB
spring.webflux.multipart.max-parts=10
