package dev.principalwater.study.data;

import java.util.List;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.simple.SimpleJdbcInsert;
import org.springframework.jdbc.core.namedparam.MapSqlParameterSource;
import org.springframework.jdbc.core.namedparam.SqlParameterSource;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

@Repository
public class NotificationDao {
    private final JdbcTemplate jdbc;
    private final SimpleJdbcInsert insert;

    public NotificationDao(JdbcTemplate jdbc) {
        this.jdbc = jdbc;
        this.insert = new SimpleJdbcInsert(jdbc).withTableName("notification")
                .usingColumns("message").usingGeneratedKeyColumns("id");
    }

    @Transactional
    public void saveNotificationsWithJdbcTemplate(List<Notification> notifications) {
        validateEntitiesHaveNoIds(notifications);
        if (notifications.isEmpty()) return;
        jdbc.batchUpdate("INSERT INTO notification (message) VALUES (?)",
                notifications.stream().map(item -> new Object[]{item.message()}).toList());
    }

    @Transactional
    public void saveNotificationsWithSimpleJdbcInsert(List<Notification> notifications) {
        validateEntitiesHaveNoIds(notifications);
        if (notifications.isEmpty()) return;
        SqlParameterSource[] parameters = notifications.stream()
                .map(item -> new MapSqlParameterSource("message", item.message()))
                .toArray(SqlParameterSource[]::new);
        insert.executeBatch(parameters);
    }

    private static void validateEntitiesHaveNoIds(List<Notification> notifications) {
        if (notifications.stream().anyMatch(item -> item.id() != null)) {
            throw new IllegalArgumentException("Notification IDs must be generated by the database");
        }
    }
}
