spring.application.name=liquibase-homework
# Настройки подключения к бд
spring.datasource.url=jdbc:h2:mem:testdb;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS yandex_practicum_homework\\;SET SCHEMA yandex_practicum_homework;
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Настройки JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.main.web-application-type=none
spring.jpa.properties.hibernate.default_schema=yandex_practicum_homework
spring.liquibase.default-schema=yandex_practicum_homework
spring.liquibase.change-log=classpath:/db/changelog/liquibase/db.changelog-master.xml
