spring.application.name=redis-lab
spring.data.redis.host=127.0.0.1
spring.data.redis.port=16381
spring.data.redis.connect-timeout=3s
spring.data.redis.timeout=3s
spring.cache.type=redis
spring.cache.redis.time-to-live=1m
