CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(256) NOT NULL,
    last_name VARCHAR(256) NOT NULL,
    age INTEGER NOT NULL CHECK (age BETWEEN 0 AND 150),
    active BOOLEAN NOT NULL
);
INSERT INTO users(first_name, last_name, age, active) VALUES
    ('Анна', 'Орлова', 30, TRUE),
    ('Илья', 'Смирнов', 25, FALSE),
    ('Мария', 'Волкова', 28, TRUE);
