CREATE TABLE account (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    balance DECIMAL(15, 2) NOT NULL DEFAULT 10000.00,
    CONSTRAINT account_balance_non_negative CHECK (balance >= 0)
) ENGINE=InnoDB;
CREATE TABLE notification (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    message VARCHAR(255) NOT NULL
) ENGINE=InnoDB;
